### ISSUE TITLE
Small documentation issue

### ISSUE THREAD

**Issue by adamstark** [HiFi-LoFi/AudioFFT#2]
Hi there,

In your README in your example code, when you initialise your real and imaginary arrays you write:

```
  std::vector<float> re(fftaudio::AudioFFT::ComplexSize(fftSize)); 
  std::vector<float> im(fftaudio::AudioFFT::ComplexSize(fftSize)); 
```

but your namespace is called 'audiofft'.

A tiny thing, but it would save others a few mins to fix it, hard to spot! :)

Great library BTW!

Thanks!

Adam

**Comment by HiFi-LoFi** [comment]
Hi Adam,

thanks a lot for reporting! I fixed this now. :-)

Regards, Uli

**Comment by philipkobernik** [comment]
It looks like the namespace is typo'd again.

Thx for the project.

Philip
