### ISSUE TITLE
Dimensions of DFT's for Intel IPP...

### ISSUE THREAD

**Issue by nicroto** [HiFi-LoFi/AudioFFT#3]
Hi,

First of all - thanks for making the AudioFFT under the MIT license.

I am trying to add support for Intel IPP.

**My issue is:**
 - I can't find anywhere in the documentation of the IPP, what is the size of the DFT produced by their algorithms.

As much as I can see, it is the same size as the input, which means it preserves the conjugate symmetries above the `N/2 + 1` mark. There are functions that would compute the DFT with "packing" to what seems to be `N/2 + 1` length, but they don't produce complex results... and this confuses me...

Any chance you have used the IPP?

Cheers!

**Comment by nicroto** [comment]
BTW, this reminds me - I don't understand this in the vDSP implementation:

    virtual void fft(const float* data, float* re, float* im) override
    {
      const size_t size2 = _size / 2;
      DSPSplitComplex splitComplex;
      splitComplex.realp = re;
      splitComplex.imagp = im;
      vDSP_ctoz(reinterpret_cast<const COMPLEX*>(data), 2, &splitComplex, 1, size2);
      ...
     }
Doesn't this get only `N/2` of the input `data`?

**Comment by nicroto** [comment]
OK, I've figured this out. I am leaving the issue open so you can let me know, whether you'd like me to make a pull request with the Intel IPP implementation.

Cheers!

**Comment by HiFi-LoFi** [comment]
Hi Nikolay,

support for Intel IPP is actually something what I'd liked to add for a long time, so your contribution would be very welcome. :-)

Regards, Uli

P.S.: I just discovered your Viktor NV1 synth, very cool! :-)
